### ISSUE TITLE
Endpoint request timed out

### ISSUE THREAD

**Issue by TheeMattOliver** [ryanjamesmcgill/congress-commentator#11]
```Unhandled rejection {"name":"StatusCodeError","statusCode":504,"message":"504 - {\"message\":\"Endpoint request timed out\"}","error":{"message":"Endpoint request timed out"},"options":{"method":"GET","uri":"https://api.propublica.org/campaign-finance/v1/2018/candidates/H2TX33040.json","json":true,"headers":{"X-API-Key":",<KEYS>"},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":504,"body":{"message":"Endpoint request timed out"},"headers":{"content-type":"application/json","content-length":"41","connection":"close","date":"Fri, 04 Jan 2019 16:23:49 GMT","x-amzn-requestid":"0c851b50-103d-11e9-bdf9-0be43b1ab0d5","x-amz-apigw-id":"S_JCwHiVIAMFnpg=","x-cache":"Error from cloudfront","via":"1.1 f4e60c374f2486c66ea3bd06264ab9ed.cloudfront.net (CloudFront)","x-amz-cf-id":"tMiKtTh6RJ02yQt-Pp1RfEJLuE4IY033OROFdz7JR8Os2zj6PBmCIg=="},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.propublica.org","port":443,"hostname":"api.propublica.org","hash":null,"search":null,"query":null,"pathname":"/campaign-finance/v1/2018/candidates/H2TX33040.json","path":"/campaign-finance/v1/2018/candidates/H2TX33040.json","href":"https://api.propublica.org/campaign-finance/v1/2018/candidates/H2TX33040.json"},"method":"GET","headers":{"X-API-Key":"<KEYS>","accept":"application/json"}}}}```

**Comment by ryanjamesmcgill** [comment]
add `async.retry`, shouldn't be an issue now.
